"""
Signal Hunter LLM Provider Abstractions and Implementations.

Defines the pluggable LLM provider architecture, enabling multi-provider support
(such as NVIDIA, Gemini, OpenAI) without altering downstream analyzer logic.
"""

import os
import re
import time
import json
import random
import logging
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
import requests

from config.config_loader import AnalyzerConfig
from utils.exceptions import SignalHunterError, AnalysisError
from utils.logger import setup_logger


class LLMProviderError(SignalHunterError):
    """Base class for all LLM provider exceptions."""
    def __init__(self, provider_name: str, message: str) -> None:
        super().__init__(f"Provider [{provider_name}] failed: {message}")
        self.provider_name = provider_name


class LLMAPIKeyError(LLMProviderError):
    """Raised when the LLM API key is missing or invalid (HTTP 401/403)."""
    pass


class LLMRateLimitError(LLMProviderError):
    """Raised when the LLM provider returns a rate limit error (HTTP 429)."""
    pass


class LLMNetworkError(LLMProviderError):
    """Raised when network connection, timeout, or transient DNS issues occur."""
    pass


class LLMValidationError(LLMProviderError):
    """Raised when the model's response is empty, malformed, or fails validation schema."""
    pass


class BaseLLMProvider(ABC):
    """
    Abstract base class for all LLM providers in Signal Hunter.
    Defines the standard interface for text generation and structured analysis.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.1,
        max_tokens: int = 1500,
    ) -> str:
        """
        Sends a generation request to the LLM and returns the raw text response.

        Args:
            prompt (str): The main prompt text.
            system_instruction (Optional[str]): Optional system behavior instruction.
            temperature (float): Sampling temperature (0.0 to 1.0).
            max_tokens (int): Maximum tokens to generate.

        Returns:
            str: Raw text generated by the model.

        Raises:
            LLMProviderError: On any failure after retries.
        """
        pass

    @abstractmethod
    def generate_structured(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.1,
        max_tokens: int = 1500,
        expected_keys: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Sends a request to the LLM and parses the response as structured JSON.
        Validates that the response is valid JSON and contains the required keys.

        Args:
            prompt (str): The main prompt text.
            system_instruction (Optional[str]): Optional system behavior instruction.
            temperature (float): Sampling temperature (0.0 to 1.0).
            max_tokens (int): Maximum tokens to generate.
            expected_keys (Optional[List[str]]): Specific keys that must exist in the parsed JSON.

        Returns:
            Dict[str, Any]: Parsed and validated JSON object.

        Raises:
            LLMProviderError: On generation or validation failure.
        """
        pass


class NvidiaProvider(BaseLLMProvider):
    """
    Official NVIDIA LLM Provider implementation.
    Connects to the OpenAI-compatible NVIDIA NIM / API catalog.
    """

    def __init__(
        self,
        config: AnalyzerConfig,
        api_url: str = "https://integrate.api.nvidia.com/v1/chat/completions",
        max_retries: int = 4,
        initial_delay: float = 1.0,
        backoff_factor: float = 2.0,
    ) -> None:
        """
        Initialize the NVIDIA Provider.

        Args:
            config (AnalyzerConfig): Configuration settings including model and temperature.
            api_url (str): Endpoint for the NVIDIA LLM service.
            max_retries (int): Maximum number of retry attempts for transient errors.
            initial_delay (float): Initial backoff delay in seconds.
            backoff_factor (float): Multiplicative factor for exponential backoff.
        """
        self.config = config
        self.api_url = api_url
        self.max_retries = max_retries
        self.initial_delay = initial_delay
        self.backoff_factor = backoff_factor

        self.logger: logging.Logger = setup_logger(
            name="signal_hunter.providers.nvidia",
            log_level="INFO",
        )

        # Retrieve API key strictly from configuration/settings object
        # Note: config loader dynamically injects environment variable if not specified in YAML
        self.api_key: Optional[str] = getattr(config, "api_key", None) or os.getenv("NVIDIA_API_KEY")

        self.model_name = config.model_name or "meta/llama-3.1-70b-instruct"

        self.logger.info(
            "NvidiaProvider initialized (Model: %s, Max Retries: %d)",
            self.model_name,
            self.max_retries,
        )

    def generate(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.1,
        max_tokens: int = 1500,
    ) -> str:
        """
        Sends a generation request to the NVIDIA API with robust retry and error handling.
        """
        if not self.api_key:
            raise LLMAPIKeyError(
                "NvidiaProvider",
                "API key is missing. Please configure NVIDIA_API_KEY in configuration or environment."
            )

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        messages = []
        if system_instruction:
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model_name,
            "messages": messages,
            "temperature": temperature if temperature is not None else self.config.temperature,
            "max_tokens": max_tokens if max_tokens is not None else self.config.max_tokens,
        }

        # Mask API key for secure logging
        masked_key = f"{self.api_key[:6]}...{self.api_key[-4:]}" if len(self.api_key) > 10 else "***"
        self.logger.info(
            "Sending NVIDIA request to model %s (Prompt length: %d chars, Key: %s)",
            self.model_name,
            len(prompt),
            masked_key,
        )

        delay = self.initial_delay
        for attempt in range(1, self.max_retries + 1):
            try:
                response = requests.post(
                    self.api_url,
                    json=payload,
                    headers=headers,
                    timeout=90.0,
                )
                
                status_code = response.status_code

                if status_code == 200:
                    try:
                        res_json = response.json()
                        text_output = res_json["choices"][0]["message"]["content"]
                        self.logger.info(
                            "NVIDIA request succeeded on attempt %d (Response length: %d chars)",
                            attempt,
                            len(text_output),
                        )
                        return text_output
                    except (KeyError, IndexError, ValueError) as e:
                        self.logger.error(
                            "NVIDIA API response format is invalid on attempt %d: %s",
                            attempt,
                            e,
                        )
                        raise LLMValidationError(
                            "NvidiaProvider",
                            f"Failed to parse text completion from API response structure: {e}"
                        ) from e

                # Handle non-200 status codes
                self.logger.warning(
                    "NVIDIA API call returned error status %d on attempt %d",
                    status_code,
                    attempt,
                )

                if status_code in (401, 403):
                    # Authentication issue: Fail immediately
                    raise LLMAPIKeyError(
                        "NvidiaProvider",
                        f"Authentication failed with status {status_code}. Please check your API key."
                    )
                
                if status_code == 429:
                    # Rate limiting: Retry with exponential backoff
                    if attempt == self.max_retries:
                        raise LLMRateLimitError(
                            "NvidiaProvider",
                            f"Rate limit exceeded (429) after {self.max_retries} attempts."
                        )
                elif status_code >= 500:
                    # Server errors: Retry
                    if attempt == self.max_retries:
                        raise LLMProviderError(
                            "NvidiaProvider",
                            f"NVIDIA Server error ({status_code}) after {self.max_retries} attempts."
                        )
                else:
                    # Client errors (400, 404, etc.): Fail immediately
                    raise LLMProviderError(
                        "NvidiaProvider",
                        f"Client error occurred with status {status_code}: {response.text}"
                    )

            except requests.exceptions.RequestException as e:
                self.logger.warning(
                    "Network error occurred on attempt %d: %s",
                    attempt,
                    e,
                )
                if attempt == self.max_retries:
                    raise LLMNetworkError(
                        "NvidiaProvider",
                        f"Network failure after {self.max_retries} attempts: {e}"
                    ) from e

            # Apply exponential backoff with jitter
            jitter = random.uniform(0.0, 0.5)
            sleep_time = delay + jitter
            self.logger.info(
                "Retrying NVIDIA API request in %.2f seconds (Attempt %d/%d)...",
                sleep_time,
                attempt + 1,
                self.max_retries,
            )
            time.sleep(sleep_time)
            delay *= self.backoff_factor

        raise LLMProviderError("NvidiaProvider", "Max retries reached without success.")

    def generate_structured(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.1,
        max_tokens: int = 1500,
        expected_keys: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Requests structured output, parses the raw string response, cleans it,
        and validates that all expected keys exist.
        """
        # Ensure the system/user instruction guides the model to output JSON
        json_guidance = "\n\nYou must respond with a single, valid JSON object ONLY. Do not include any extra conversational text."
        if expected_keys:
            json_guidance += f" The JSON object must contain these exact keys: {expected_keys}."

        full_prompt = prompt + json_guidance

        # Call the underlying API generator
        raw_response = self.generate(
            prompt=full_prompt,
            system_instruction=system_instruction,
            temperature=temperature,
            max_tokens=max_tokens,
        )

        # 1. Clean response if wrapped in markdown formatting blocks
        cleaned_text = raw_response.strip()
        # Regex to strip ```json ... ``` blocks
        match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned_text)
        if match:
            cleaned_text = match.group(1).strip()

        # 2. Parse JSON
        try:
            parsed_json = json.loads(cleaned_text)
        except json.JSONDecodeError as e:
            self.logger.error(
                "Failed to decode response as JSON. Raw: %s",
                raw_response[:500],
            )
            raise LLMValidationError(
                "NvidiaProvider",
                f"Model response is not valid JSON: {e}. Raw content: {raw_response[:300]}"
            ) from e

        # 3. Validate presence of expected keys
        if expected_keys:
            missing_keys = [key for key in expected_keys if key not in parsed_json]
            if missing_keys:
                self.logger.error(
                    "JSON response failed validation. Missing keys: %s. Parsed keys: %s",
                    missing_keys,
                    list(parsed_json.keys()),
                )
                raise LLMValidationError(
                    "NvidiaProvider",
                    f"JSON response is missing required keys: {missing_keys}"
                )

        self.logger.info("Successfully validated JSON response.")
        return parsed_json


class GeminiProvider(BaseLLMProvider):
    """
    Google Gemini LLM Provider implementation using standard REST API.
    Does not require any specialized google client library, maintaining ultra-high stability.
    """

    def __init__(
        self,
        config: AnalyzerConfig,
        max_retries: int = 2,
        initial_delay: float = 1.0,
        backoff_factor: float = 2.0,
    ) -> None:
        """
        Initialize the Gemini Provider.
        """
        self.config = config
        self.max_retries = max_retries
        self.initial_delay = initial_delay
        self.backoff_factor = backoff_factor

        self.logger: logging.Logger = setup_logger(
            name="signal_hunter.providers.gemini",
            log_level="INFO",
        )

        # Retrieve API key strictly from environment
        self.api_key: Optional[str] = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY") or os.getenv("GOOGLE_GENAI_API_KEY")

        self.model_name = getattr(config, "model_name", "gemini-3.5-flash")
        if not self.model_name or "meta/" in self.model_name or "gemini-2.5" in self.model_name:
            self.model_name = "gemini-3.5-flash"

        self.logger.info(
            "GeminiProvider initialized (Model: %s, Max Retries: %d)",
            self.model_name,
            self.max_retries,
        )

    def generate(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.1,
        max_tokens: int = 1500,
    ) -> str:
        """
        Sends a generation request to the Gemini API with retry and backoff handling.
        """
        if not self.api_key:
            raise LLMAPIKeyError(
                "GeminiProvider",
                "GEMINI_API_KEY is missing. Please configure it in your environment."
            )

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        headers = {"Content-Type": "application/json"}

        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": temperature if temperature is not None else self.config.temperature,
                "maxOutputTokens": max_tokens if max_tokens is not None else self.config.max_tokens,
            }
        }
        if system_instruction:
            payload["systemInstruction"] = {"parts": [{"text": system_instruction}]}

        masked_key = f"{self.api_key[:6]}...{self.api_key[-4:]}" if len(self.api_key) > 10 else "***"
        self.logger.info(
            "Sending Gemini request to model %s (Prompt length: %d chars, Key: %s)",
            self.model_name,
            len(prompt),
            masked_key,
        )

        delay = self.initial_delay
        for attempt in range(1, self.max_retries + 1):
            try:
                response = requests.post(
                    url,
                    json=payload,
                    headers=headers,
                    timeout=15.0,
                )
                status_code = response.status_code

                if status_code == 200:
                    try:
                        res_json = response.json()
                        text_output = res_json["candidates"][0]["content"]["parts"][0]["text"]
                        self.logger.info(
                            "Gemini request succeeded on attempt %d (Response length: %d chars)",
                            attempt,
                            len(text_output),
                        )
                        return text_output
                    except (KeyError, IndexError, ValueError) as e:
                        self.logger.error(
                            "Gemini API response format is invalid on attempt %d: %s",
                            attempt,
                            e,
                        )
                        raise LLMValidationError(
                            "GeminiProvider",
                            f"Failed to parse text completion from Gemini response: {e}"
                        ) from e

                # Handle errors
                self.logger.warning("Gemini API call returned error status %d on attempt %d", status_code, attempt)

                if status_code in (401, 403):
                    raise LLMAPIKeyError("GeminiProvider", f"Authentication failed with status {status_code}.")
                if status_code == 429:
                    if attempt == self.max_retries:
                        raise LLMRateLimitError("GeminiProvider", f"Rate limit exceeded after {self.max_retries} attempts.")
                elif status_code >= 500:
                    if attempt == self.max_retries:
                        raise LLMProviderError("GeminiProvider", f"Gemini Server error ({status_code}) after {self.max_retries} attempts.")
                else:
                    raise LLMProviderError("GeminiProvider", f"Client error with status {status_code}: {response.text}")

            except requests.exceptions.RequestException as e:
                self.logger.warning("Network error occurred on attempt %d: %s", attempt, e)
                if attempt == self.max_retries:
                    raise LLMNetworkError("GeminiProvider", f"Network failure: {e}") from e

            # Backoff
            jitter = random.uniform(0.0, 0.5)
            sleep_time = delay + jitter
            time.sleep(sleep_time)
            delay *= self.backoff_factor

        raise LLMProviderError("GeminiProvider", "Max retries reached without success.")

    def generate_structured(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.1,
        max_tokens: int = 1500,
        expected_keys: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Requests structured output from Gemini using its native JSON response feature,
        then validates the required fields are present.
        """
        if not self.api_key:
            raise LLMAPIKeyError(
                "GeminiProvider",
                "GEMINI_API_KEY is missing. Please configure it in your environment."
            )

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        headers = {"Content-Type": "application/json"}

        # Instruct model on JSON expectations
        json_guidance = "\n\nYou must respond with a single, valid JSON object ONLY. Do not include any extra conversational text."
        if expected_keys:
            json_guidance += f" The JSON object must contain these exact keys: {expected_keys}."

        full_prompt = prompt + json_guidance

        payload = {
            "contents": [{"parts": [{"text": full_prompt}]}],
            "generationConfig": {
                "temperature": temperature if temperature is not None else self.config.temperature,
                "maxOutputTokens": max_tokens if max_tokens is not None else self.config.max_tokens,
                "responseMimeType": "application/json",  # Force native JSON parsing
            }
        }
        if system_instruction:
            payload["systemInstruction"] = {"parts": [{"text": system_instruction}]}

        masked_key = f"{self.api_key[:6]}...{self.api_key[-4:]}" if len(self.api_key) > 10 else "***"
        self.logger.info(
            "Sending structured Gemini request to model %s (Prompt length: %d chars, Key: %s)",
            self.model_name,
            len(full_prompt),
            masked_key,
        )

        delay = self.initial_delay
        for attempt in range(1, self.max_retries + 1):
            try:
                response = requests.post(
                    url,
                    json=payload,
                    headers=headers,
                    timeout=15.0,
                )
                status_code = response.status_code

                if status_code == 200:
                    try:
                        res_json = response.json()
                        text_output = res_json["candidates"][0]["content"]["parts"][0]["text"].strip()
                        
                        # Clean markdown wrappers if any are present despite responseMimeType
                        match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text_output)
                        if match:
                            text_output = match.group(1).strip()

                        parsed_json = json.loads(text_output)

                        # Validate expected keys
                        if expected_keys:
                            missing_keys = [key for key in expected_keys if key not in parsed_json]
                            if missing_keys:
                                raise LLMValidationError(
                                    "GeminiProvider",
                                    f"JSON response is missing required keys: {missing_keys}"
                                )

                        self.logger.info("Successfully parsed and validated Gemini structured JSON response.")
                        return parsed_json

                    except (KeyError, IndexError, ValueError, json.JSONDecodeError) as e:
                        self.logger.error("Failed to parse/validate Gemini response on attempt %d: %s", attempt, e)
                        raise LLMValidationError(
                            "GeminiProvider",
                            f"JSON structure parsing failed: {e}"
                        ) from e

                # Handle errors
                if status_code in (401, 403):
                    raise LLMAPIKeyError("GeminiProvider", f"Authentication failed with status {status_code}.")
                if status_code == 429:
                    if attempt == self.max_retries:
                        raise LLMRateLimitError("GeminiProvider", f"Rate limit exceeded after {self.max_retries} attempts.")
                elif status_code >= 500:
                    if attempt == self.max_retries:
                        raise LLMProviderError("GeminiProvider", f"Gemini Server error ({status_code}) after {self.max_retries} attempts.")
                else:
                    raise LLMProviderError("GeminiProvider", f"Client error with status {status_code}: {response.text}")

            except requests.exceptions.RequestException as e:
                self.logger.warning("Network error occurred on attempt %d: %s", attempt, e)
                if attempt == self.max_retries:
                    raise LLMNetworkError("GeminiProvider", f"Network failure: {e}") from e

            # Backoff
            jitter = random.uniform(0.0, 0.5)
            sleep_time = delay + jitter
            time.sleep(sleep_time)
            delay *= self.backoff_factor

        raise LLMProviderError("GeminiProvider", "Max retries reached without success.")

